/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface C3Burning {
        "bgColor": number;
        "height": number;
        "width": number;
    }
}
declare global {
    interface HTMLC3BurningElement extends Components.C3Burning, HTMLStencilElement {
    }
    var HTMLC3BurningElement: {
        prototype: HTMLC3BurningElement;
        new (): HTMLC3BurningElement;
    };
    interface HTMLElementTagNameMap {
        "c3-burning": HTMLC3BurningElement;
    }
}
declare namespace LocalJSX {
    interface C3Burning {
        "bgColor"?: number;
        "height"?: number;
        "width"?: number;
    }
    interface IntrinsicElements {
        "c3-burning": C3Burning;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "c3-burning": LocalJSX.C3Burning & JSXBase.HTMLAttributes<HTMLC3BurningElement>;
        }
    }
}
